import fs from 'fs';
import path from 'path';

const demoDir = path.join(__dirname, '..', 'api', 'demo');
const outDir = path.join(__dirname, '..', 'src');

const template = fs.readFileSync(path.join(demoDir, 'template.html'), 'utf-8');
const styles = fs.readFileSync(path.join(demoDir, 'styles.css'), 'utf-8');
const script = fs.readFileSync(path.join(demoDir, 'client.script'), 'utf-8');

const content = `// AUTO-GENERATED by scripts/gen-demo.ts — do not edit
export const demoTemplate = ${JSON.stringify(template)};
export const demoStyles = ${JSON.stringify(styles)};
export const demoScript = ${JSON.stringify(script)};
`;

fs.writeFileSync(path.join(outDir, 'demo-content.ts'), content);
console.log('Generated src/demo-content.ts');
